%% Creating Plots to Verify Dataset Conversion %%

% Author: Anthony Anderson. Seattle, WA.
% Matlab 2020b

%{

After converting the database, I wanted to verify that everything worked
the way I thought it did. This script makes a few plots that can be
compared to the scripts generated by MAIN_Python.

I've selected three trials to plot some signals that can be compared across
the two file formats. If the signals look the same, we know that the
conversion was successful.

%}

clear; close all; clc;

%% Figure 1: Subject AB06 IK on levelground

% trial information
subject = "AB06\";
condition = "levelground\";
date = "10_09_18\";
signal = "ik\";
labels = "conditions\";
file = "levelground_ccw_normal_01_01";

% construct paths to data and labels
data_path = "matlab data\" + subject + date + condition + signal + file;
label_path = "matlab data\" + subject + date + condition + labels + file;

% load inverse kinematics data
ik_data = load(data_path);
ik_data = ik_data.data;

% load activity labels
label_data = load(label_path);
label_data = label_data.labels;

% extract time and labels
label_time = label_data.('Header');
label = label_data.('Label');
label = string(label);

% convert labels
label_map = zeros(length(label), 1);
label_map(label=="idle") = 0;
label_map(label=="stand") = 1;
label_map(label=="stand-walk") = 2;
label_map(label=="walk") = 3;
label_map(label=="turn2") = 4;
label_map(label=="turn1") = 5;
label_map(label=="walk-stand") = 6;

% extract ankle angle
ik_time = ik_data.('Header');
ankle_angle = ik_data.('ankle_angle_r');
knee_angle = ik_data.('knee_angle_r');

% make the plot
figure()
subplot(3, 1, 1)
plot(label_time, label_map, 'Color', '#4357AD')
ylim([-0.5, 6.5])
xlim([7, 30])
title('AB06, levelground\_ccw\_normal\_01\_01')
ylabel('Label')
grid on

subplot(3, 1, 2)
plot(ik_time, ankle_angle, 'Color', '#48A9A6')
xlim([8, 30])
ylabel('Ankle Angle (deg)')
grid on

subplot(3, 1, 3)
plot(ik_time, -knee_angle, 'Color', '#C1666B')
xlim([8, 30])
ylabel('Knee Angle (deg)')
xlabel('Time (s)')
grid on

%% Figure 2:

% trial information
subject = "AB15\";
condition = "treadmill\";
date = "11_07_2018\";
signal = "imu\";
speed = "conditions\";
file = "treadmill_05_01";

% construct paths to data and labels
data_path = "matlab data\" + subject + date + condition + signal + file;
speed_path = "matlab data\" + subject + date + condition + speed + file;

% load imu data
imu_data = load(data_path);
imu_data = imu_data.data;

% load activity labels
speed_data = load(speed_path);
speed_data = speed_data.speed;

% extract time and speed
speed_time = speed_data.('Header');
speed = speed_data.('Speed');

% extract imu signals
ax = imu_data.('shank_Accel_X');
ay = imu_data.('shank_Accel_Y');
az = imu_data.('shank_Accel_Z');
gx = imu_data.('shank_Gyro_X');
gy = imu_data.('shank_Gyro_Y');
gz = imu_data.('shank_Gyro_Z');
t = imu_data.('Header');

figure()
subplot(3, 1, 1)
plot(speed_time, speed, 'Color', 'k')
ylim([0.25, 2.25])
xlim([42.5, 85])
title('AB15, treadmill\_05\_01')
ylabel('Treadmill Speed (m/s)')
grid on

subplot(3, 1, 2)
plot(t, ax, 'Color', '#E8C547')
hold on
plot(t, ay, 'Color', '#124E78')
plot(t, az, 'Color', '#A63A50')
xlim([42.5, 85])
ylabel('Shamk Accel (g)')
grid on

subplot(3, 1, 3)
plot(t, gx, 'Color', '#E8C547')
hold on
plot(t, gy, 'Color', '#124E78')
plot(t, gz, 'Color', '#A63A50')
xlim([42.5, 85])
ylabel('Shank Gyro (rad/s)')
grid on
xlabel('Time (s)')

%% Figure 3

% trial information
subject = "AB30\";
condition = "stair\";
date = "03_09_2019\";
emg = "emg\";
markers = "markers\";
file = "stair_1_r_01_01";

% construct paths to data and labels
emg_path = "matlab data\" + subject + date + condition + emg + file;
marker_path = "matlab data\" + subject + date + condition + markers + file;

% load emg and marker data
emg_data = load(emg_path);
emg_data = emg_data.data;
marker_data = load(marker_path);
marker_data = marker_data.data;

% extract emg signals
t1 = emg_data.('Header');
soleus = emg_data.('soleus');
glute_med = emg_data.('gluteusmedius');

soleus_rect = abs(soleus);
glute_med_rect = abs(glute_med);

[b, a] = butter(4, 5/500);
sol_env = filtfilt(b, a, soleus_rect);
glute_med_env = filtfilt(b, a, glute_med_rect);

% get markers
t0 = marker_data.('Header');
r_heel_y = marker_data.('R_Heel_y');
r_toe_y = marker_data.('R_Toe_Tip_y');

% plot
figure()
subplot(3, 1, 1)
plot(t0, r_heel_y, 'Color', '#445E93')
hold on
plot(t0, r_toe_y, 'Color', '#524632')
legend('heel', 'toe')
title('AB30, stair\_1\_r\_01\_01')
ylabel('Height (mm)')
grid on

subplot(3, 1, 2)
plot(t1, soleus, 'Color', '#86CB92')
hold on
plot(t1, sol_env, 'Color', 'k')
legend('raw', 'linear envelope')
ylabel('Soleus EMG (mV)')
grid on

subplot(3, 1, 3)
plot(t1, glute_med, 'Color', '#FE654F')
hold on
plot(t1, glute_med_env, 'Color', 'k')
legend('raw', 'linear envelope')
ylabel('Glute EMG (mV)')
grid on
xlabel('Time (s)')

